---
- name: Kubernetes Copy using Ansible
  hosts: one
  tasks:
    - name: kubernetes copy
      become: true
      copy:
        src: ./kubernetes
        dest: ./
        owner: ansible_usr
        group: ansible_usr
        mode: 0644
    # - name: Minikube Delete
    #   command: minikube delete
    - name: Minikube
      command: minikube start
    - name: Apply backend secret file
      command: kubectl apply -f kubernetes/msfyv-backend-secret.yaml
    - name: Apply backend
      command: kubectl apply -f kubernetes/msfyv-backend.yaml
    - name: Service
      command: minikube service msfyv-backend-service
    - name: Apply frontend configmap
      command: kubectl apply -f kubernetes/msfyv-frontend-configmap.yaml
    - name: Frontend Service
      command: kubectl apply -f kubernetes/msfyv-frontend.yaml
    - name: Execute the script
      script: kubernetes/test.sh