---
- name: Kubernetes Copy using Ansible
  hosts: one
  tasks:
    - name: kubernetes copy
      become: true
      copy:
        src: ./kubernetes
        dest: ./
        owner: ansible_usr
        group: ansible_usr
        mode: 0644
    - name: Minikube
      command: minikube start
    - name: Apply backend secret file
      command: kubectl apply -f kubernetes/msfyv-backend-secret.yaml
    - name: Apply backend
      command: kubectl apply -f kubernetes/msfyv-backend.yaml
    # - name: Host IP
    #   command: export my_ip=$(ip route get 8.8.8.8 | awk '{ print $7; exit }')
    - name: Port Forwarding Backend
      command: kubectl port-forward --address localhost,172.16.132.90 service/msfyv-backend-service 5001:5001