---
- name: Kubernetes Copy using Ansible
  hosts: one
  tasks:
    - name: kubernetes copy
      become: true
      copy:
        src: ./kubernetes
        dest: ./
        owner: ansible_usr
        group: ansible_usr
        mode: 0644