apiVersion: v1
kind: Secret
metadata:
  name: msfyv-backend-secret
type: Opaque
data:
  PORT: NTAwMQ==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9uYWdwYWw4Nzk1OlNFa0xpaEJaWjh5N1ltZ0BzcGUuY2lwcTZuaC5tb25nb2RiLm5ldC9TUEU/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5